version: '3.8'

services:
    db:
        image: postgres:14.5
        restart: on-failure
        expose:
            - 5432
        ports:
            - "5987:5432"
        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql
        env_file:
            - ./bot/.env

    redis:
        image: redis:7.0.4
        restart: always
        command: redis-server --appendonly yes --replica-read-only no
        expose:
            - 6379
        ports:
            - "6379:6379"
        volumes:
            - ./dbs/redis-data:/data/

    bot:
        build: ./bot
        container_name: trading_bot
        restart: always
        expose:
            - 3001
        ports:
            - "3001:3001"
        depends_on:
            - db
        volumes:
            - ./bot:/bot
        command: bash -c "
            alembic upgrade head &&
            python3 main.py"
        env_file:
            - ./bot/.env
